// <auto-generated />
using GpsCoordinatesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GpsCoordinatesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GpsCoordinatesApi.Models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coordinates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 47.497900000000001,
                            Longitude = 19.040199999999999,
                            Name = "Start Budapest",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 47.4985,
                            Longitude = 19.042000000000002,
                            Name = "Point 2",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 47.5,
                            Longitude = 19.045000000000002,
                            Name = "Point 3",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 47.500999999999998,
                            Longitude = 19.047999999999998,
                            Name = "Point 4",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = 5,
                            Latitude = 47.502000000000002,
                            Longitude = 19.050000000000001,
                            Name = "Point 5",
                            OrderIndex = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
